# Generated by Django 6.1 on 2026-09-18 08:47

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survival', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurvivalAttempt',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_number', models.PositiveSmallIntegerField()),
                ('attempt_number', models.PositiveIntegerField()),
                ('survival_day', models.PositiveIntegerField()),
                ('score', models.PositiveIntegerField(default=0)),
                ('result', models.CharField(choices=[('WIN', 'Win'), ('LOSS', 'Loss'), ('DEATH', 'Death'), ('RESET', 'Reset'), ('TIMEOUT', 'Timeout')], max_length=20)),
                ('is_death', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('survival_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_history', to='survival.survivalrun')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SurvivalLevelProgress',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_number', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('LOCKED', 'Locked'), ('AVAILABLE', 'Available'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='LOCKED', max_length=20)),
                ('best_score', models.PositiveIntegerField(default=0)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('deaths', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('survival_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_progress', to='survival.survivalrun')),
            ],
            options={
                'ordering': ['level_number'],
                'constraints': [models.UniqueConstraint(fields=('survival_run', 'level_number'), name='unique_survival_run_level')],
            },
        ),
    ]
