# Generated by Django 6.1 on 2026-09-18 08:50

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survival', '0002_survivalattempt_survivallevelprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurvivalInventory',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.BooleanField(default=False)),
                ('map_collected', models.BooleanField(default=False)),
                ('fuel_can', models.BooleanField(default=False)),
                ('key_1', models.BooleanField(default=False)),
                ('key_2', models.BooleanField(default=False)),
                ('key_3', models.BooleanField(default=False)),
                ('glass_bridge_completed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('survival_run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='survival.survivalrun')),
            ],
        ),
    ]
