# Generated by Django 6.1 on 2026-09-19 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survival', '0003_survivalinventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survivalattempt',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='survivallevelprogress',
            name='best_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='survivalrun',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
    ]
